### ISSUE TITLE
Question: Join new worker to existing cluster

### ISSUE THREAD

**Issue by hxhieu** [siderolabs/contrib#47]
Hi and thanks for the work,

I have followed the `basic` example and have the nodes up on a Proxmox cluster.
So now I would like to spin up another worker node for this same cluster, normally I would just `talosctl apply-config -n ... -file worker.yaml`

However, the `worker.yaml` was generated by the `talosctl gen` command instead and when using this Terraform setup I don't have that.

How could I join another worker node now?

Thanks.

**Comment by smira** [comment]
With Terraform, you just add a node and do `terraform apply` (or whatever makes sense in your case).

**Comment by hxhieu** [comment]
Right makes sense and I will give it a try. Thanks.
