### ISSUE TITLE
workload proxy does not work for the on-prem omni examples

### ISSUE THREAD

**Issue by Roguito** [siderolabs/contrib#56]
it generates UID.proxy-us.mydomain.tld which creates issues. I am playing with the --workload-proxying-subdomain argument right now and will update with more information if I can figure it out and will contribute additional omni example documentation accordingly.

Adding it as an issue right now so I can track this.

**Comment by dealerflow** [comment]
Rebuilding my omni Jumpstart server. This isn't stale.

**Comment by Roguito** [comment]
--workload-proxying-subdomain=''

cannot be empty as it create omni..mydomain.com URLs. I have not tested null but I suspect, even if the docker/docker-compose ecosystem when combined with your env allows null assissignments.

I set the subdomain to proxy and then setup a wildcard CNAME to my omni instance and seems to work.

[closing this]
